collections_config:
  products:
    name: Products
    path: src/products
    output: true
    url: /products/[slug]/
    _inputs:
      tags:
        type: hidden
        defaultValue: products
      title:
        type: text
        comment: Product Name
      price:
        type: number
      image:
        type: image
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      description:
        type: markdown
      is_new:
        type: checkbox
        label: "¿Es Nuevo?"
      is_bestseller:
        type: checkbox
        label: "¿Es Más Vendido?"

  gallery:
    name: Galería
    path: src/gallery
    output: false
    _inputs:
      tags:
        type: hidden
        defaultValue: gallery
      title:
        type: text
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      image:
        type: image
