collections_config:
  products:
    name: Products
    path: src/products
    output: true
    url: /products/[slug]/
    schema_key: default
    schemas:
      default:
        path: schemas/product.md
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    _inputs:
      title:
        type: text
        comment: Product Name
      price:
        type: number
      image:
        type: image
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      description:
        type: markdown
      is_new:
        type: checkbox
        label: "¿Es Nuevo?"
      is_bestseller:
        type: checkbox
        label: "¿Es Más Vendido?"

  gallery:
    name: Galería
    path: src/gallery
    output: false
    schema_key: default
    schemas:
      default:
        path: schemas/gallery.md
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    _inputs:
      title:
        type: text
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      image:
        type: image
