collections_config:
  products:
    name: Products
    path: src/products
    output: true
    url: /products/[slug]/
    schema_key: default
    schemas:
      default:
        path: schemas/product.md
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    _inputs:
      tags:
        type: text
        hidden: true
      title:
        type: text
        comment: Product Name
      price:
        type: number
      image:
        type: image
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      description:
        type: markdown
      is_new:
        type: checkbox
        label: "¿Es Nuevo?"
      is_bestseller:
        type: checkbox
        label: "¿Es Más Vendido?"

  gallery:
    name: Galería
    path: src/gallery
    output: false
    schema_key: default
    schemas:
      default:
        path: schemas/gallery.md
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    _inputs:
      title:
        type: text
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      image:
        type: image

  faq:
    name: Preguntas Frecuentes
    path: src/faq
    output: false
    schema_key: default
    schemas:
      default:
        path: schemas/faq.md
    create:
      path: '[relative_base_path]/{pregunta|slugify}.md'
    _inputs:
      tags:
        type: text
        hidden: true
      pregunta:
        type: text
        label: Pregunta
      respuesta:
        type: textarea
        label: Respuesta
      orden:
        type: number
        label: Orden de visualización

data_config:
  site:
    path: src/_data/site.json
    _inputs:
      customizeImage:
        type: image
        label: Imagen para "Cómo Comprar - Personalizado"
        comment: Esta imagen aparece en la pestaña de personalización

paths:
  uploads: src/assets/img
  dam_uploads: src/assets/img
  dam_static: ''

_inputs:
  image:
    type: image
    options:
      paths:
        uploads: src/assets/img
        dam_uploads: src/assets/img
