collections_config:
  products:
    name: Products
    path: src/products
    output: true
    url: /products/[slug]/
    _inputs:
      title:
        type: text
        comment: Product Name
      price:
        type: number
      image:
        type: image
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
      description:
        type: markdown
      is_new:
        type: checkbox
        label: "¿Es Nuevo?"
      is_bestseller:
        type: checkbox
        label: "¿Es Más Vendido?"

items_config:
  gallery:
    path: src/_data/gallery.json
    type: json
    parser: json
    _inputs:
      category:
        type: select
        options:
          values:
            - "Camisas"
            - "Tazas"
            - "Botellas"
            - "Llaveros"
            - "Cuadros"
            - "Otros"
    schema:
      type: array
      items:
        type: object
        properties:
          title: { type: string }
          category: { type: string }
          image: { type: image }
